language: java
jdk:
 - oraclejdk8
services:
  - docker
before_install:
  - docker image build -t vaznok/postgres .
  - docker container run --name postgresdb -d -p 5555:5432 -e POSTGRES_PASSWORD=root vaznok/postgres
  - docker container start postgresdb
script:
 - mvn clean verify